laravel/app/Http/routes.php
        return redirect()->route('aulas.grade-de-aulas.index');
    });

    Route::group(['prefix' => 'a-solum'], function () {
        Route::get('/', 'HistoricoController@index')
                ->name('a-solum.index');
        Route::get('historico', 'HistoricoController@index')
                ->name('a-solum.historico');
        Route::get('estrutura', 'EstruturaController@index')
                ->name('a-solum.estrutura');
        Route::get('professores', 'ProfessoresController@index')
                ->name('a-solum.professores.index');
        Route::get('professores/{professor_slug}', 'ProfessoresController@show')
                ->name('a-solum.professores.show');
        Route::get('vantagens', 'VantagensController@index')
                ->name('a-solum.vantagens');
        Route::get('videos-e-fotos', 'VideosEFotosController@index')
                ->name('a-solum.videos-e-fotos.index');
        Route::get('videos-e-fotos/ritmo/{ritmo_slug?}', 'VideosEFotosController@ritmo')
                ->name('a-solum.videos-e-fotos.ritmo');
        Route::get('videos-e-fotos/busca', 'VideosEFotosController@busca')
                ->name('a-solum.videos-e-fotos.busca');
        Route::get('videos-e-fotos/{galeria_slug}', 'VideosEFotosController@show')
                ->name('a-solum.videos-e-fotos.show');
    });

    Route::group(['prefix' => 'aulas'], function () {
        Route::get('/', 'RitmosController@index')
                ->name('aulas.index');
        Route::get('ritmos/{ritmo_slug?}', 'RitmosController@index')
                ->name('aulas.ritmos');
        Route::get('grade-de-aulas', 'GradeDeAulasController@index')
                ->name('aulas.grade-de-aulas.index');
        Route::get('grade-de-aulas/ritmo/{ritmo_slug?}', 'GradeDeAulasController@ritmo')
                ->name('aulas.grade-de-aulas.ritmo');
        Route::get('grade-de-aulas/{grade_de_aulas}', 'GradeDeAulasController@show')
                ->name('aulas.grade-de-aulas.show');
        Route::get('cursos-regulares', 'CursosRegularesController@index')
                ->name('aulas.cursos-regulares');
        Route::get('cursos-intensivos', 'CursosIntensivosController@index')
                ->name('aulas.cursos-intensivos');
        Route::get('cursos-intensivos/{intensivo_id}', 'CursosIntensivosController@curso')
                ->name('aulas.cursos-intensivos.curso');
        Route::get('precos', 'PrecosController@index')
                ->name('aulas.precos');
    });

    Route::group(['prefix' => 'calendario'], function () {
        Route::get('/', 'EventosController@index')
                ->name('calendario.index');
        Route::get('eventos', 'EventosController@index')
                ->name('calendario.eventos');
        Route::get('turmas-e-aulas', 'TurmasEAulasController@index')
                ->name('calendario.turmas-e-aulas');
    });

    Route::get('mais-servicos/{mais_servicos_slug?}', 'MaisServicosController@index')
            ->name('mais-servicos');

    Route::group(['prefix' => 'mural'], function () {
        Route::get('/', 'AvisosController@index')
                ->name('mural.index');
        Route::get('avisos', 'AvisosController@index')
                ->name('mural.avisos');
        Route::get('onde-dancar', 'OndeDancarController@index')
                ->name('mural.onde-dancar');
        Route::get('onde-comprar', 'OndeComprarController@index')
                ->name('mural.onde-comprar');
        Route::get('enquete', 'EnquetesController@index')
                ->name('mural.enquetes');
        Route::get('enquete/votar/{opcao?}', 'EnquetesController@formVotar')
                ->name('mural.enquetes.formVotar');
        Route::post('enquete/votar', 'EnquetesController@votar')
                ->name('mural.enquetes.votar');
        Route::get('enquete/{enquetes}', 'EnquetesController@resultados')
                ->name('mural.enquetes.resultados');
    });

    Route::group(['prefix' => 'localizacao'], function () {
        Route::get('/', 'ComoChegarController@index')
                ->name('localizacao.index');
        Route::get('como-chegar', 'ComoChegarController@index')
                ->name('localizacao.como-chegar');
        Route::get('hospedagem', 'HospedagemController@index')
                ->name('localizacao.hospedagem');
    });

    Route::get('fale-conosco', 'FaleConoscoController@index')
            ->name('fale-conosco.index');
    Route::post('fale-conosco', 'FaleConoscoController@post')
            ->name('fale-conosco.post');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        // HOME
        Route::resource('home/banners', 'BannersController');
        Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
        Route::resource('home/videos', 'VideosHomeController');

        // A SOLUM
        Route::resource('a-solum/historico', 'HistoricoController', ['only' => ['index', 'update']]);
        Route::get('a-solum/historico/imagens/clear', [
            'as'   => 'painel.a-solum.historico.imagens.clear',
            'uses' => 'HistoricoImagensController@clear'
        ]);
        Route::resource('a-solum/historico/imagens-laterais', 'HistoricoImagensLateraisController');
        Route::resource('a-solum/historico/imagens', 'HistoricoImagensController');
        Route::resource('a-solum/estrutura', 'EstruturaController', ['only' => ['index', 'update']]);
        Route::get('a-solum/estrutura/imagens/clear', [
            'as'   => 'painel.a-solum.estrutura.imagens.clear',
            'uses' => 'EstruturaImagensController@clear'
        ]);
        Route::resource('a-solum/estrutura/imagens-laterais', 'EstruturaImagensLateraisController');
        Route::resource('a-solum/estrutura/imagens', 'EstruturaImagensController');
        Route::resource('a-solum/professores', 'ProfessoresController');
        Route::resource('a-solum/professores.videos', 'ProfessoresVideosController');
        Route::get('a-solum/professores/{professores}/imagens/clear', [
            'as'   => 'painel.a-solum.professores.imagens.clear',
            'uses' => 'ProfessoresImagensController@clear'
        ]);
        Route::resource('a-solum/professores.imagens', 'ProfessoresImagensController');
        Route::resource('a-solum/vantagens', 'VantagensController', ['only' => ['index', 'update']]);
        Route::get('a-solum/vantagens/imagens/clear', [
            'as'   => 'painel.a-solum.vantagens.imagens.clear',
            'uses' => 'VantagensImagensController@clear'
        ]);
        Route::resource('a-solum/vantagens/imagens-laterais', 'VantagensImagensLateraisController');
        Route::resource('a-solum/vantagens/imagens', 'VantagensImagensController');
        Route::resource('a-solum/videos-e-fotos', 'VideosEFotosController');
        Route::resource('a-solum/videos-e-fotos.videos', 'VideosEFotosVideosController');
        Route::get('a-solum/videos-e-fotos/{videos_e_fotos}/imagens/clear', [
            'as'   => 'painel.a-solum.videos-e-fotos.imagens.clear',
            'uses' => 'VideosEFotosImagensController@clear'
        ]);
        Route::resource('a-solum/videos-e-fotos.imagens', 'VideosEFotosImagensController');

        // AULAS
        Route::resource('aulas/ritmos', 'RitmosController');
        Route::resource('aulas/ritmos.videos', 'RitmosVideosController');
        Route::resource('aulas/cursos-regulares', 'CursosRegularesController', ['only' => ['index', 'update']]);
        Route::resource('aulas/cursos-regulares/imagens-laterais', 'CursosRegularesImagensLateraisController');
        Route::resource('aulas/cursos-intensivos/chamada', 'CursosIntensivosChamadaController', ['only' => ['index', 'update']]);
        Route::resource('aulas/cursos-intensivos', 'CursosIntensivosController');
        Route::resource('aulas/precos', 'PrecosController');
        Route::resource('aulas/promocoes', 'PromocoesController');

        // GRADE DE AULAS
        Route::resource('aulas/grade-de-aulas/niveis', 'NiveisController');
        Route::get('aulas/grade-de-aulas', 'GradeDeAulasController@index')->name('painel.aulas.grade-de-aulas.index');
        Route::post('aulas/grade-de-aulas', 'GradeDeAulasController@store')->name('painel.aulas.grade-de-aulas.store');
        Route::get('aulas/grade-de-aulas/get-ritmos', 'GradeDeAulasController@ritmos')->name('painel.aulas.grade-de-aulas.getRitmos');
        Route::get('aulas/grade-de-aulas/get-niveis', 'GradeDeAulasController@niveis')->name('painel.aulas.grade-de-aulas.getNiveis');
        Route::post('aulas/grade-de-aulas/update', 'GradeDeAulasController@update')->name('painel.aulas.grade-de-aulas.update');
        Route::delete('aulas/grade-de-aulas/{grade_de_aulas}', 'GradeDeAulasController@destroy')->name('painel.aulas.grade-de-aulas.destroy');

        // CALENDÁRIO
        Route::resource('calendario/turmas-e-aulas', 'TurmasEAulasController');
        Route::resource('calendario/eventos', 'EventosController');

        // MAIS SERVIÇOS
        Route::resource('mais-servicos', 'MaisServicosController');
        Route::get('mais-servicos/{mais_servicos}/imagens/clear', [
            'as'   => 'painel.mais-servicos.imagens.clear',
            'uses' => 'MaisServicosImagensController@clear'
        ]);
        Route::resource('mais-servicos.imagens-laterais', 'MaisServicosImagensLateraisController');
        Route::resource('mais-servicos.imagens', 'MaisServicosImagensController');

        // MURAL
        Route::resource('mural/avisos', 'AvisosController');
        Route::resource('mural/onde-comprar', 'OndeComprarController');
        Route::resource('mural/onde-dancar', 'OndeDancarController');
        Route::resource('mural/enquetes', 'EnquetesController');

laravel/app/Http/Controllers/OndeComprarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\EstabelecimentoCompra;

class OndeComprarController extends Controller
{
    public function index()
    {
        return view('frontend.mural.onde-comprar')->with([
            'estabelecimentos' => EstabelecimentoCompra::ordenados()->get(),
        ]);
    }
}

laravel/app/Http/Controllers/Painel/AvisosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AvisosRequest;
use App\Http\Controllers\Controller;

use App\Models\Aviso;

class AvisosController extends Controller
{
    public function index()
    {
        $registros = Aviso::ordenados()->get();

        return view('painel.avisos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.avisos.create')->with([
            'categorias' => Aviso::categorias()
        ]);
    }

    public function store(AvisosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['notificacao']) && $input['notificacao'] != '') {
                $this->enviaNotificacao(
                    Aviso::categorias()[$input['categoria']],
                    $input['notificacao']
                );
            }

            Aviso::create($input);

            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function edit(Aviso $registro)
    {
        $categorias = Aviso::categorias();
        return view('painel.avisos.edit', compact('registro', 'categorias'));
    }

    public function update(AvisosRequest $request, Aviso $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function destroy(Aviso $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    private function enviaNotificacao($titulo, $mensagem)
    {
        $headers = [
            'Authorization: key=AAAAPvrRvt4:APA91bH7HRjixBchx1DcxyoW3UI7xTFELPT9t0g1kY4S0n7jkYgFVfwTc_mzhcrQHMbRGHa-vbVabHZM5xw9JOA-UljyHzbN9Lu6ij0DpVDmnWeo1Fz5E-oao9ZXWHT8XQPqZYE9lWsL',
            'Content-Type: application/json'
        ];

        $data = [
            'notification' => [
                'title' => $titulo,
                'body'  => $mensagem
            ],
            'to'           => '/topics/avisos',
            'priority'     => 'high'
        ];

        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
        curl_setopt($ch,CURLOPT_POST, true);
        curl_setopt($ch,CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch,CURLOPT_POSTFIELDS, json_encode($data));
        $result = curl_exec($ch);
        curl_close($ch);

        $json = json_decode($result);

        if (!isset($json->message_id)) {
            throw new \Exception('Erro ao enviar notificação. Tente novamente.', 1);
        }
    }

}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.home.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ComoChegarController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ComoChegarRequest;
use App\Http\Controllers\Controller;

use App\Models\ComoChegar;

class ComoChegarController extends Controller
{
    public function index()
    {
        $registro = ComoChegar::first();

        return view('painel.como-chegar.edit', compact('registro'));
    }

    public function update(ComoChegarRequest $request, ComoChegar $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = ComoChegar::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.localizacao.como-chegar.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/onde-comprar/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Mural / Onde Comprar /</small> Adicionar Estabelecimento</h2>
    </legend>

    {!! Form::open(['route' => 'painel.mural.onde-comprar.store', 'files' => true]) !!}

        @include('painel.onde-comprar.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/onde-comprar/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Mural / Onde Comprar /</small> Editar Estabelecimento</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.mural.onde-comprar.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.onde-comprar.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/onde-comprar/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/onde-comprar/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('endereco', 'Endereço') !!}
    {!! Form::textarea('endereco', null, ['class' => 'form-control ckeditor', 'data-editor' => 'comoChegarEndereco']) !!}
</div>

<div class="form-group">
    {!! Form::label('telefone', 'Telefone') !!}
    {!! Form::text('telefone', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('observacoes', 'Observações') !!}
    {!! Form::textarea('observacoes', null, ['class' => 'form-control ckeditor', 'data-editor' => 'comoChegarEndereco']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.mural.onde-comprar.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/onde-comprar/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            <small>Mural /</small> Onde Comprar
            <a href="{{ route('painel.mural.onde-comprar.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Estabelecimento</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="onde_comprar">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Nome</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->nome }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.mural.onde-comprar.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.mural.onde-comprar.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection