laravel/app/Http/routes.php
        Route::get('videos-e-fotos/{galeria_slug}', 'VideosEFotosController@show')
                ->name('a-solum.videos-e-fotos.show');
    });

    Route::group(['prefix' => 'aulas'], function () {
        Route::get('/', 'RitmosController@index')
                ->name('aulas.index');
        Route::get('ritmos/{ritmo_slug?}', 'RitmosController@index')
                ->name('aulas.ritmos');
        Route::get('grade-de-aulas', 'GradeDeAulasController@index')
                ->name('aulas.grade-de-aulas.index');
        Route::get('grade-de-aulas/ritmo/{ritmo_slug?}', 'GradeDeAulasController@ritmo')
                ->name('aulas.grade-de-aulas.ritmo');
        Route::get('grade-de-aulas/{grade_de_aulas}', 'GradeDeAulasController@show')
                ->name('aulas.grade-de-aulas.show');
        Route::get('cursos-regulares', 'CursosRegularesController@index')
                ->name('aulas.cursos-regulares');
        Route::get('cursos-intensivos', 'CursosIntensivosController@index')
                ->name('aulas.cursos-intensivos');
        Route::get('cursos-intensivos/{intensivo_id}', 'CursosIntensivosController@curso')
                ->name('aulas.cursos-intensivos.curso');
        Route::get('precos', 'PrecosController@index')
                ->name('aulas.precos');
    });

    Route::group(['prefix' => 'calendario'], function () {
        Route::get('/', 'EventosController@index')
                ->name('calendario.index');
        Route::get('eventos', 'EventosController@index')
                ->name('calendario.eventos');
        Route::get('turmas-e-aulas', 'TurmasEAulasController@index')
                ->name('calendario.turmas-e-aulas');
    });

    Route::get('mais-servicos/{mais_servicos_slug?}', 'MaisServicosController@index')
            ->name('mais-servicos');

    Route::group(['prefix' => 'mural'], function () {
        Route::get('/', 'AvisosController@index')
                ->name('mural.index');
        Route::get('avisos', 'AvisosController@index')
                ->name('mural.avisos');
        Route::get('onde-dancar', 'OndeDancarController@index')
                ->name('mural.onde-dancar');
        Route::get('onde-comprar', 'OndeComprarController@index')
                ->name('mural.onde-comprar');
        Route::get('enquete', 'EnquetesController@index')
                ->name('mural.enquetes');
        Route::get('enquete/votar/{opcao?}', 'EnquetesController@formVotar')
                ->name('mural.enquetes.formVotar');
        Route::post('enquete/votar', 'EnquetesController@votar')
                ->name('mural.enquetes.votar');
        Route::get('enquete/{enquetes}', 'EnquetesController@resultados')
                ->name('mural.enquetes.resultados');
    });

    Route::group(['prefix' => 'localizacao'], function () {
        Route::get('/', 'ComoChegarController@index')
                ->name('localizacao.index');
        Route::get('como-chegar', 'ComoChegarController@index')
                ->name('localizacao.como-chegar');
        Route::get('hospedagem', 'HospedagemController@index')
                ->name('localizacao.hospedagem');
    });

    Route::get('fale-conosco', 'FaleConoscoController@index')
            ->name('fale-conosco.index');
    Route::post('fale-conosco', 'FaleConoscoController@post')
            ->name('fale-conosco.post');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        // HOME
        Route::resource('home/banners', 'BannersController');
        Route::resource('home/chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
        Route::resource('home/videos', 'VideosHomeController');

        // A SOLUM
        Route::resource('a-solum/historico', 'HistoricoController', ['only' => ['index', 'update']]);
        Route::get('a-solum/historico/imagens/clear', [
            'as'   => 'painel.a-solum.historico.imagens.clear',
            'uses' => 'HistoricoImagensController@clear'
        ]);
        Route::resource('a-solum/historico/imagens-laterais', 'HistoricoImagensLateraisController');
        Route::resource('a-solum/historico/imagens', 'HistoricoImagensController');
        Route::resource('a-solum/estrutura', 'EstruturaController', ['only' => ['index', 'update']]);
        Route::get('a-solum/estrutura/imagens/clear', [
            'as'   => 'painel.a-solum.estrutura.imagens.clear',
            'uses' => 'EstruturaImagensController@clear'
        ]);
        Route::resource('a-solum/estrutura/imagens-laterais', 'EstruturaImagensLateraisController');
        Route::resource('a-solum/estrutura/imagens', 'EstruturaImagensController');
        Route::resource('a-solum/professores', 'ProfessoresController');
        Route::resource('a-solum/professores.videos', 'ProfessoresVideosController');
        Route::get('a-solum/professores/{professores}/imagens/clear', [
            'as'   => 'painel.a-solum.professores.imagens.clear',
            'uses' => 'ProfessoresImagensController@clear'
        ]);
        Route::resource('a-solum/professores.imagens', 'ProfessoresImagensController');
        Route::resource('a-solum/vantagens', 'VantagensController', ['only' => ['index', 'update']]);
        Route::get('a-solum/vantagens/imagens/clear', [
            'as'   => 'painel.a-solum.vantagens.imagens.clear',
            'uses' => 'VantagensImagensController@clear'
        ]);
        Route::resource('a-solum/vantagens/imagens-laterais', 'VantagensImagensLateraisController');
        Route::resource('a-solum/vantagens/imagens', 'VantagensImagensController');
        Route::resource('a-solum/videos-e-fotos', 'VideosEFotosController');
        Route::resource('a-solum/videos-e-fotos.videos', 'VideosEFotosVideosController');
        Route::get('a-solum/videos-e-fotos/{videos_e_fotos}/imagens/clear', [
            'as'   => 'painel.a-solum.videos-e-fotos.imagens.clear',
            'uses' => 'VideosEFotosImagensController@clear'
        ]);
        Route::resource('a-solum/videos-e-fotos.imagens', 'VideosEFotosImagensController');

        // AULAS
        Route::resource('aulas/ritmos', 'RitmosController');
        Route::resource('aulas/ritmos.videos', 'RitmosVideosController');
        Route::resource('aulas/cursos-regulares', 'CursosRegularesController', ['only' => ['index', 'update']]);
        Route::resource('aulas/cursos-regulares/imagens-laterais', 'CursosRegularesImagensLateraisController');
        Route::resource('aulas/cursos-intensivos/chamada', 'CursosIntensivosChamadaController', ['only' => ['index', 'update']]);
        Route::resource('aulas/cursos-intensivos', 'CursosIntensivosController');
        Route::resource('aulas/precos', 'PrecosController');
        Route::resource('aulas/promocoes', 'PromocoesController');

        // GRADE DE AULAS
        Route::resource('aulas/grade-de-aulas/niveis', 'NiveisController');
        Route::get('aulas/grade-de-aulas', 'GradeDeAulasController@index')->name('painel.aulas.grade-de-aulas.index');
        Route::post('aulas/grade-de-aulas', 'GradeDeAulasController@store')->name('painel.aulas.grade-de-aulas.store');
        Route::get('aulas/grade-de-aulas/get-ritmos', 'GradeDeAulasController@ritmos')->name('painel.aulas.grade-de-aulas.getRitmos');
        Route::get('aulas/grade-de-aulas/get-niveis', 'GradeDeAulasController@niveis')->name('painel.aulas.grade-de-aulas.getNiveis');
        Route::post('aulas/grade-de-aulas/update', 'GradeDeAulasController@update')->name('painel.aulas.grade-de-aulas.update');
        Route::delete('aulas/grade-de-aulas/{grade_de_aulas}', 'GradeDeAulasController@destroy')->name('painel.aulas.grade-de-aulas.destroy');

        // CALENDÁRIO
        Route::resource('calendario/turmas-e-aulas', 'TurmasEAulasController');
        Route::resource('calendario/eventos', 'EventosController');

        // MAIS SERVIÇOS
        Route::resource('mais-servicos', 'MaisServicosController');
        Route::get('mais-servicos/{mais_servicos}/imagens/clear', [
            'as'   => 'painel.mais-servicos.imagens.clear',
            'uses' => 'MaisServicosImagensController@clear'
        ]);
        Route::resource('mais-servicos.imagens-laterais', 'MaisServicosImagensLateraisController');
        Route::resource('mais-servicos.imagens', 'MaisServicosImagensController');

        // MURAL
        Route::resource('mural/avisos', 'AvisosController');
        Route::resource('mural/onde-comprar', 'OndeComprarController');
        Route::resource('mural/onde-dancar', 'OndeDancarController');
        Route::resource('mural/enquetes', 'EnquetesController');
        Route::get('mural/enquetes/ativar/{enquetes}', 'EnquetesController@ativar')->name('painel.mural.enquetes.ativar');

        // LOCALIZAÇÃO
        Route::resource('localizacao/hospedagem', 'HospedagemController');
        Route::resource('localizacao/como-chegar', 'ComoChegarController', ['only' => ['index', 'update']]);

        // CONTATO
        Route::resource('contato/respostas-automaticas', 'RespostasAutomaticasController');
        Route::get('contatos/recebidos/exportar', 'ContatosRecebidosController@exportar')->name('painel.contato.recebidos.exportar');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');

        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');

laravel/app/Http/Controllers/Painel/AvisosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AvisosRequest;
use App\Http\Controllers\Controller;

use App\Models\Aviso;

class AvisosController extends Controller
{
    public function index()
    {
        $registros = Aviso::ordenados()->get();

        return view('painel.avisos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.avisos.create')->with([
            'categorias' => Aviso::categorias()
        ]);
    }

    public function store(AvisosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['notificacao']) && $input['notificacao'] != '') {
                $this->enviaNotificacao(
                    Aviso::categorias()[$input['categoria']],
                    $input['notificacao']
                );
            }

            Aviso::create($input);

            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function edit(Aviso $registro)
    {
        $categorias = Aviso::categorias();
        return view('painel.avisos.edit', compact('registro', 'categorias'));
    }

    public function update(AvisosRequest $request, Aviso $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()])->withInput();

        }
    }

    public function destroy(Aviso $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.mural.avisos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    private function enviaNotificacao($titulo, $mensagem)
    {
        $headers = [
            'Authorization: key=AAAAPvrRvt4:APA91bH7HRjixBchx1DcxyoW3UI7xTFELPT9t0g1kY4S0n7jkYgFVfwTc_mzhcrQHMbRGHa-vbVabHZM5xw9JOA-UljyHzbN9Lu6ij0DpVDmnWeo1Fz5E-oao9ZXWHT8XQPqZYE9lWsL',
            'Content-Type: application/json'
        ];

        $data = [
            'notification' => [
                'title' => $titulo,
                'body'  => $mensagem
            ],
            'to'           => '/topics/avisos',
            'priority'     => 'high'
        ];

        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
        curl_setopt($ch,CURLOPT_POST, true);
        curl_setopt($ch,CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch,CURLOPT_POSTFIELDS, json_encode($data));
        $result = curl_exec($ch);
        curl_close($ch);

        $json = json_decode($result);

        if (!isset($json->message_id)) {
            throw new \Exception('Erro ao enviar notificação. Tente novamente.', 1);
        }
    }

}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.home.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.home.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ComoChegarController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ComoChegarRequest;
use App\Http\Controllers\Controller;

use App\Models\ComoChegar;

class ComoChegarController extends Controller
{
    public function index()
    {
        $registro = ComoChegar::first();

        return view('painel.como-chegar.edit', compact('registro'));
    }

    public function update(ComoChegarRequest $request, ComoChegar $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = ComoChegar::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.localizacao.como-chegar.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(str_is('painel.home*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.home.banners*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.home.banners.index') }}">Banners</a>
            </li>
        	<li @if(str_is('painel.home.chamadas*', Route::currentRouteName())) class="active" @endif>
        		<a href="{{ route('painel.home.chamadas.index') }}">Chamadas</a>
        	</li>
            <li @if(str_is('painel.home.videos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.home.videos.index') }}">Vídeos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.a-solum*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            A Solum
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.a-solum.historico*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.a-solum.historico.index') }}">Histórico</a>
            </li>
            <li @if(str_is('painel.a-solum.estrutura*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.a-solum.estrutura.index') }}">Estrutura</a>
            </li>
            <li @if(str_is('painel.a-solum.professores*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.a-solum.professores.index') }}">Professores</a>
            </li>
            <li @if(str_is('painel.a-solum.vantagens*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.a-solum.vantagens.index') }}">Vantagens</a>
            </li>
            <li @if(str_is('painel.a-solum.videos-e-fotos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.a-solum.videos-e-fotos.index') }}">Vídeos e Fotos</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.aulas*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Aulas
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.aulas.ritmos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.ritmos.index') }}">Ritmos</a>
            </li>
            <li @if(str_is('painel.aulas.grade-de-aulas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.grade-de-aulas.index') }}">Grade de Aulas</a>
            </li>
            <li @if(str_is('painel.aulas.cursos-regulares*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.cursos-regulares.index') }}">Cursos Regulares</a>
            </li>
            <li @if(str_is('painel.aulas.cursos-intensivos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.cursos-intensivos.index') }}">Cursos Intensivos</a>
            </li>
            <li @if(str_is('painel.aulas.precos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.precos.index') }}">Preços</a>
            </li>
            <li @if(str_is('painel.aulas.promocoes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aulas.promocoes.index') }}">Promoções</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.calendario*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Calendário
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.calendario.eventos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.calendario.eventos.index') }}">Eventos</a>
            </li>
            <li @if(str_is('painel.calendario.turmas-e-aulas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.calendario.turmas-e-aulas.index') }}">Turmas e Aulas</a>
            </li>
        </ul>
    </li>

    <li @if(str_is('painel.mais-servicos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.mais-servicos.index') }}">Mais Serviços</a>
    </li>

    <li class="dropdown @if(str_is('painel.mural*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Mural
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.mural.avisos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.mural.avisos.index') }}">Avisos</a>
            </li>
            <li @if(str_is('painel.mural.onde-dancar*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.mural.onde-dancar.index') }}">Onde Dançar</a>
            </li>
            <li @if(str_is('painel.mural.onde-comprar*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.mural.onde-comprar.index') }}">Onde Comprar</a>
            </li>
            <li @if(str_is('painel.mural.enquetes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.mural.enquetes.index') }}">Enquetes</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.localizacao*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Localização
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.localizacao.como-chegar*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.localizacao.como-chegar.index') }}">Como Chegar</a>
            </li>
            <li @if(str_is('painel.localizacao.hospedagem*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.localizacao.hospedagem.index') }}">Hospedagem</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.contato.index', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(str_is('painel.contato.respostas-automaticas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.contato.respostas-automaticas.index') }}">Respostas Automáticas</a>
            </li>
            <li @if(str_is('painel.contato.recebidos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
</ul>